### ISSUE TITLE
Weird background size when phone restarts

### ISSUE THREAD

**Issue by zeusent** [Polyphian/repo#4]
Hi! First of all let me tell you that I thinks this shortcut is genius :) I love the out of the box thinking!

I just wanted to let you know that whenever I restart my phone the image shown on the Lock Screen has a weird size.

Running Wetr fixes it. I use a manually selected album with just one specific photo in it in my configuration.

Here’s 2 screenshots to compare:

![37DD9277-91A8-464E-AA66-0D89B9866FE8](https://user-images.githubusercontent.com/777591/146149754-86e849bd-67dd-4807-84ee-34cb89b8b42a.png)
![1E379D93-7EC0-4DDA-802C-635DC936D6D8](https://user-images.githubusercontent.com/777591/146149779-858c5f4b-897e-478f-b983-8871ab07d806.png)

**Comment by Polyphian** [comment]
This is an iOS issue. Most nights iOS soft reboots overnight to free up and refresh its resources. Has been doing this since iOS 11 I think. Nothing I can do about it. You'll need to file this feedback with apple. 

Thank you.

**Comment by zeusent** [comment]
Well, when I manually set the same photo as the lock screen background it doesn’t do that 🙄 That’s weird 🤔

On 15 Dec 2021, at 18:47, Polyphian ***@***.***> wrote:

﻿

This is an iOS issue. Most nights iOS soft reboots overnight to free up and refresh its resources. Has been doing this since iOS 11 I think. Nothing I can do about it. You'll need to file this feedback with apple.

Thank you.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPolyphian%2Frepo%2Fissues%2F4%23issuecomment-994971913&data=04%7C01%7C%7Cc93366940474492907f008d9bfea947e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637751836498800728%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YfyvcNyrdbFNV0%2FtDlZDdMNX50%2FN9pmea%2FsO6BGeBnE%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAF525ZMHW2L2CUW3WPQJQ3URDBCBANCNFSM5KC7L6PA&data=04%7C01%7C%7Cc93366940474492907f008d9bfea947e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637751836498810721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Ry1uPGgiGjlXPlpeFBZICKcJJsmrazBAtMmlNaA1CP8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cc93366940474492907f008d9bfea947e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637751836498810721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9aGA0NYcetVe8RjZ1NAm9W8f%2F4sSHz7mZ3QYZYnw7UA%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cc93366940474492907f008d9bfea947e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637751836498820715%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ov%2F4SVHBU4Z61IUKbSacwutwSqX3hTkJ8J2f3XCFdEw%3D&reserved=0>.
